### ISSUE TITLE
Remove R-value area weighting?

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-ResStock#19]
Currently, we are (surface) area-weighting R-values for: wall insulation, attic insulation, slab insulation, etc.

**Comment by joseph-robertson** [comment]
Craig and Scott think we should. @ewilson, your thoughts?

**Comment by ejhw** [comment]
@jrobert1 Yes, sounds good to me.

**Comment by shorowit** [comment]
@joseph-robertson This can be closed?

**Comment by joseph-robertson** [comment]
Yes.
