### ISSUE TITLE
Consolidate H1 regions?

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-ResStock#20]
@cchriste proposes that we consolidate H1C1 OR, H1C1 WA, H1C2, and H1C3 into a single H1 region. Decision pending.

cc @jrobert1 @ewilson

**Comment by joseph-robertson** [comment]
One advantage of keeping OR and WA separate (at least for H1), is that it could capture differences related to code adoption. E.g., 
usmap

**Comment by joseph-robertson** [comment]
I doubt 2009 vs 2012 codes would even be a blip in the RBSA data. Though it could suggest a general trend of WA adopting codes before OR.

Seems like it'd be better to look at the RBSA queried results and see if there are significant differences in, e.g., insulation levels between the two states.

**Comment by joseph-robertson** [comment]
Also, remember that we are no longer required to have every parameter tied to the same regions anymore. For example, if the envelope varied between WA and OR, we could make insulation parameters dependent on those regions while leaving other parameters (e.g., HVAC) dependent on heating zones.

**Comment by joseph-robertson** [comment]
@ewilson, @shorowit,

Does this help in capturing differences between WA and OR?

Insulation Wall
image

**Comment by joseph-robertson** [comment]
@jrobert1: Can you split the above table by heating zone so that we get tables specific to H1, H2, and H3? And do it for walls, attics, and windows? And commit text files instead of using images.

**Comment by joseph-robertson** [comment]
@cchriste is going to revisit the mapping for wall insulation. Percentages of R-13 walls for pre-1950s homes seems large.

**Comment by shorowit** [comment]
Completed.
