### ISSUE TITLE
Duct options

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-ResStock#21]
There are very high weighting factors for "In Finished Space".

In one of Eric's recent commits (09c04e6), he added a comment regarding when we assume ducts are in finished space. Sounds like we need to revisit?

@jrobert1 @ewilson

**Comment by joseph-robertson** [comment]
Ducts are on @ejhw's to do list.

**Comment by shorowit** [comment]
@joseph-robertson It seems like we should not have a "None" duct option in the Ducts.tsv file (see national-scale version for reference). The airflow measure will automatically override the duct specification with no ducts if there is no ducted HVAC system. With the way things are now, you can get a ducted HVAC system in the house but without ducts.

**Comment by joseph-robertson** [comment]
@ejhw Have you had a chance to look at the `assign_ducts()` method in util.py yet?

So far we look at two RBSA tables: SFducts and SFducttesting_dbase. We get duct insulation type and duct location from SFducts. We get duct blaster results from SFducttesting_dbase.

The way it is in util.py right now, we assign "In Finished Space" (or soon to become "None") whenever duct insulation is NULL or whenever there are no duct blaster results.

Seems to me a duct blaster test would only be performed on ducts that are not in conditioned space (?) If this is the case, then we should never return "None" if there is an entry in the SFducttesting_dbase table. Also I think we could look to the SFducts table to determine whether there are ducts in unconditioned space (even if a duct blaster wasn't performed).

**Comment by shorowit** [comment]
"or soon to become None": See my comment above where I recommended we never assign to None. We can discuss if need be.

**Comment by joseph-robertson** [comment]
Ok. There are some `# FIXME: Change to 'None'` comments in the code.

**Comment by ejhw** [comment]
I'm reviewing now. My intention behind `# FIXME: Change to 'None'` was that the row/sample should not be counted in the query since the home did not receive a duct leakage test (which only 250 homes did). So maybe it should say `Change to NULL`.

**Comment by joseph-robertson** [comment]
@ejhw See [Ducts Analysis.zip](https://github.com/NREL/OpenStudio-ResStock/files/542311/Ducts.Analysis.zip)

![test1](https://cloud.githubusercontent.com/assets/8516790/19569769/2812b3c0-96b4-11e6-9944-dab65d0cd5de.png)
![test2](https://cloud.githubusercontent.com/assets/8516790/19569773/29bb3a3a-96b4-11e6-9ae6-0ea1cd61ae21.png)
![test3](https://cloud.githubusercontent.com/assets/8516790/19569777/2d627f54-96b4-11e6-80d9-01ccebb71f41.png)

**Comment by ejhw** [comment]
> It seems like we should not have a "None" duct option in the Ducts.tsv file (see national-scale version for reference). The airflow measure will automatically override the duct specification with no ducts if there is no ducted HVAC system. With the way things are now, you can get a ducted HVAC system in the house but without ducts.

@shorowit, if I'm understanding your comment correctly, the Ducts.tsv should be constructed based on homes with ducted HVAC only (and the Airflow measure will override as appropriate). In other words, if there are three homes: 

| Home | Ducted HVAC | Ducts                    |
|------|-------------|--------------------------|
| 1    | True        | In Finished Space        |
| 2    | True        | 20% Leakage, Uninsulated |
| 3    | False       | N/A                      |

Then the weighting factors would be based on homes 1 and 2 only (as opposed to including home 3 as `In Finished Space`):

| Option                   | Weight |
|--------------------------|--------|
| In Finished Space        | 50%    |
| 20% Leakage, Uninsulated | 50%    |

Correct?

**Comment by shorowit** [comment]
@ejhw Yes, that sounds right to me. I was assuming that's how the queries were updated when the None option was removed, I'm not sure how else the query could be structured?

**Comment by ejhw** [comment]
Addressed in https://github.com/NREL/OpenStudio-ResStock/commit/72c4b5b8dd8ba7b60d57a4832e5af8485f800337 
options_lookup.tsv and Airflow.tsv will need to be updated.

@shorowit, how should we handle the fact that these duct options are different than for National-scale? Do we need to split options_lookup.tsv?

**Comment by shorowit** [comment]
You can put all of the options across both national/pnw in options_lookup.tsv.

The only complexity comes if you want the same option names between national & pnw but different values -- e.g., if you have an "average" heating setpoint option name that maps to different setpoints for the two versions, or a house size option name that maps to different floor areas. The easiest way to solve this would be to use slightly different names (e.g., "PNW average" vs "National average" for the setpoint example).

**Comment by ejhw** [comment]
Ah, that makes sense. Thanks. I'll update the tsv files.

**Comment by ejhw** [comment]
Craig checked with Ben Larson: high levels of insulated ducts is apparently what they saw in the field.
Eric is waiting to hear back from Iain Walker about access to LBNL ducts database, which could be used to double-check these distributions and update the national values.
