### ISSUE TITLE
PNW HVAC modeling challenges

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-ResStock#22]
- [x] Wood/pellet stoves as primary/secondary: 126/545 samples (RBSA shows no backup systems)
- [x] Dual fuel heat pumps: 18 samples
- [x] GSHP - 14 samples
- [x] Radiant floor / heated slab
- [x] Model PTACs separately or model as RoomAC? How many PTACs in non-multifamily?
- [x] Need way to specify Electric Baseboard for MSHP homes
- [x] Electric space heaters (JR: pretty sure we're modeling 'pluginheater' as Electric Baseboard (?))

**Comment by shorowit** [comment]
Using surrogate technology models. Options labeled as FIXME until we develop actual OpenStudio measures.
