### ISSUE TITLE
Change Custom Region definitions

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-ResStock#24]
I think we'd like to change the following regions to make them more ordered by climate. Some of our materials (characteristics spreadsheet for external users) already have this change made.

New England: from 4 to 3
Great Lakes: from 5 to 4
Mountain North: from 3 to 5
cc @shorowit 

<img width="1108" alt="custom regions map" src="https://cloud.githubusercontent.com/assets/1276021/17783431/4281cc2e-6535-11e6-9e7d-9af3acbbb90f.png">

**Comment by shorowit** [comment]
Seems straight-forward to change. Are you asking us to go ahead and do it, or is a final decision pending?

**Comment by ejhw** [comment]
Let's go ahead and do it.
