### ISSUE TITLE
Script to compare RBSA consumption data to simulation results

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-ResStock#30]
* Method to query TMY3-normalized RBSA consumption data (Measured data)
* Method to retrieve simulated energy use from analysis results (Predicted data)
* Per house electricity/gas plots, sliced by:
  * [x] Location Heating Region
  * [x] Vintage
  * [x] Heating Fuel
  * [x] Location Heating Region and Vintage
* Plots of electricity + gas, sliced by:
  * [x] Location Heating Region
  * [x] Vintage
  * [x] Heating Fuel

To be reviewed by @ejhw.

**Comment by ejhw** [comment]
@joseph-robertson, if you have some time, I think it would be nice to make some comparisons of consumption histograms, such as the ones produced by the `draw_histograms()` method in the `Load Plotting Functions.ipynb` file that I sent you:
<img width="505" alt="screen shot 2016-12-01 at 3 09 33 pm" src="https://cloud.githubusercontent.com/assets/1276021/20814793/6ddb325c-b7d8-11e6-892c-ba0a6b634117.png">
You could try both histograms and kde (kernel density estimates) to see which comparison is more useful (http://seaborn.pydata.org/examples/distplot_options.html). We could also make these for various vintage and H-zone slices.
