### ISSUE TITLE
Update probability distributions

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-ResStock#31]
Need to update some parameters (due to bin changes for house size and # stories):
- [x] Geometry House Size.tsv
- [x] Geometry Stories.tsv - National
- [x] Geometry Garage.tsv - National & PNW (use National for both)
- [x] Geometry.tsv
- [ ] Infiltration.tsv - National

We can't do any new runs until these are updated.

**Comment by ejhw** [comment]
Idea: change from CR to RD for RECS queries cc @jalley71

**Comment by ejhw** [comment]
Stories: Use Vintage and Size only @joseph-robertson

**Comment by joseph-robertson** [comment]
@jalley71 Infiltration.tsv in the resources/inputs/national folder has incorrect set of geometry house sizes.

**Comment by ejhw** [comment]
@joseph-robertson, we can use this one until the updated infiltration tsv is ready: https://github.com/NREL/OpenStudio-ResStock/blob/master/data/recs/RECS%20STUFF/Probability%20Distributions/Infiltration.tsv
