### ISSUE TITLE
PNW Heating and Cooling Setpoints

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-ResStock#35]
Below I'm comparing setpoints from audit data (HeatTemp, HeatTempNight, ACTemp, ACNight) to indoor temperature from meter data (IDT).

For each metered home, I used a very simple clustering approach (with n=2 clusters) to identify a "min" setpoint and a "max" setpoint. I used DEC, JAN, FEB data for the heating setpoint min and max clusters, and JUN, JUL, AUG for the cooling setpoint min and max clusters.

In general, I think the resident-reported setback for heating aligns with the meter data better than the setup for cooling.

Heating
![image](https://cloud.githubusercontent.com/assets/8516790/20016102/be1285be-a283-11e6-95ec-8b9df65596a1.png)
Cooling
![image](https://cloud.githubusercontent.com/assets/8516790/20016104/c11964a8-a283-11e6-8395-77cf41899e08.png)
@shorowit @craigch99

**Comment by shorowit** [comment]
@joseph-robertson Pretty interesting. Based on those graphs, it's clearly important to capture heating setback but cooling setups are less obvious.

For Heating Setpoint.tsv, I recommend that you:
- [ ] Add dependencies on Location Heating Region and Vintage
- [ ] Rename the options from, e.g., "65F" to, e.g., "65F w/setback"
- [ ] Update the probability distributions in Heating Setpoint.tsv via RBSA queries
- [ ] For each bin in Heating Setpoint.tsv (i.e., each combination of Location Heating Region, Vintage, and setpoint option), query RBSA for the average setback value and attach the results here

**Comment by shorowit** [comment]
@craigch99 I'm seeing SEEM runs with 10pm-6am heating setbacks. Is that consistent with what you see in the SEEM calibration files?

**Comment by craigch99** [comment]
Yes, except that it is actually 9pm to 7am, because it’s hours 10,11,12,1,2,3,4,5,6 for a total of 9 hours.

[cid:image002.jpg@01D239B1.B4699A60]

Regards,
Craig Christensen
Principal Engineer
National Renewable Energy Laboratory
303-384-7510 (office)
303-241-4570 (cell)

**Comment by shorowit** [comment]
Hmm, are you seeing something different than me? I see "hour to set down to lower T" is 22 and "hour to set up to higher T" is 6. I don't see how this would be interpreted as you did.

**Comment by shorowit** [comment]
Image from Craig:

![setpoint_schedule](https://cloud.githubusercontent.com/assets/5861765/20114029/1af6f808-a5b0-11e6-97c3-2c8bc33f4108.jpg)

**Comment by shorowit** [comment]
@joseph-robertson Thanks, this is all really helpful. Here's where we are:
- [ ] As there were no clear trends for heating setpoint based on zone and/or vintage, please revert to having no dependencies.
- [ ] There is a correlation between setpoint and setback, so we will use different setbacks for each setpoint. Can you query the single average setback for each heating setpoint bin?

@craigch99 There's also a question as to whether we need to have setback and non-setback options, or should just assume setbacks in all homes as was done in the SEEM Calibration work. Craig is going to explore how many homes have setbacks reported.

**Comment by joseph-robertson** [comment]
@shorowit Can i go ahead and commit stuff, or am I still waiting for conflicts to be resolved, etc.?

**Comment by shorowit** [comment]
We're good, proceed.

**Comment by shorowit** [comment]
Looks good, thanks!
