### ISSUE TITLE
None Heating Systems

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-ResStock#36]
We have moderate percentages of buildings with no HVAC heating systems in the PNW. I assume this is because of systems that we can't currently model? We really shouldn't map these to None, because we're ending up with building simulations without heating.

I think we should either:
1. Add options for these other technologies (and model them with the closest technology approximation)
2. Ignore these buildings and redistribute the probabilities of non-None options to 100% (and perhaps reduce the total house count)

Thoughts?

cc @joseph-robertson @craigch99 @ejhw

**Comment by shorowit** [comment]
For example, buildings without heat pumps have 34% for the None option for H1, 1980s, electrically heated homes. @joseph-robertson can you list out the heating systems that make up this bin? The only electric HVAC option we're missing according to [this ticket ](https://github.com/NREL/OpenStudio-ResStock/issues/22)is electric space heaters.

**Comment by joseph-robertson** [comment]
Here are some examples for when we have no heating system:
* Heat pumps with no HSPF (e.g., 10011)
* htstove (10016)
* Oil furnace (10087)
* fireplace (10915)
* Furnaces with no CombEffic (24863)

**Comment by joseph-robertson** [comment]
For Location Heating Region=H1, Heating Fuel=Electricity, HVAC System Is Combined=No, Vintage=1980s, here are the systems that are mapped to the None option:
* Heat pumps with no HSPF (13169, 21414, 22993, 23028, 24436)

**Comment by shorowit** [comment]
Why isn't that excluded based on HVAC System Is Combined=No?

**Comment by joseph-robertson** [comment]
Not sure what you mean.

**Comment by shorowit** [comment]
We've decided to go with option 1. So:
- [ ] @joseph-robertson We should break up the None option in HVAC System Heating into the actual options that they are -- e.g., Wood Stove, Dual-Fuel ASHP, GSHP, etc., with an efficiency value if possible. The None option will therefore be 1 for HVAC System Is Combined=Yes rows and 0 for HVAC System Is Combined=No rows.
- [ ] I will map the options to similar technology models.
