### ISSUE TITLE
Can't specify some upgrades

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-ResStock#38]
Upgrades that refer to the AirflowOriginalModel measure won't run because it's an EnergyPlus measure. To accommodate it now, we'd have to create an EnergyPlus measure version of the ApplyUpgrade measure, which is a real pain. Instead, we'll wait on https://github.com/NREL/OpenStudio-BEopt/issues/40 and switch to the Airflow measure when we can.

This affects: ducts, infiltration, mechanical ventilation, attic insulation, crawlspace insulation, water heaters, HVAC heating systems, and clothes dryers.

The example attic insulation upgrade in the analysis spreadsheets has been temporarily switched to a wall insulation upgrade.

**Comment by joseph-robertson** [comment]
NREL/OpenStudio-BEopt#40 has been addressed: the airflow measure has been updated to use `SurfaceProperty:ConvectionCoefficients`.

@shorowit

**Comment by shorowit** [comment]
@joseph-robertson We are waiting on an OpenStudio 2.0 docker image that we can use. We're stuck with 1.14 at the moment.

**Comment by shorowit** [comment]
No longer a problem.
